python3 show_result.py --mode single --bench-name Activity
python3 show_result.py --mode single --bench-name Forecast
python3 show_result.py --mode single --bench-name Localization/location
python3 show_result.py --mode single --bench-name Localization/spatial
python3 show_result.py --mode single --bench-name Object/affordance
python3 show_result.py --mode single --bench-name Object/attribute
python3 show_result.py --mode single --bench-name Object/existence
python3 show_result.py --mode single --bench-name Planning/assistance
python3 show_result.py --mode single --bench-name Planning/navigation
python3 show_result.py --mode single --bench-name Reasoning/comparing
python3 show_result.py --mode single --bench-name Reasoning/counting
python3 show_result.py --mode single --bench-name Reasoning/situated